name: armm_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+3

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  app_settings: ^5.1.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.3
  cloud_functions: ^5.1.3
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.1.0
  dio: ^5.4.1
  file_picker: ^8.0.0+1
  file_saver: ^0.2.12
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.0.1
  flutter_lints: ^4.0.0
  flutter_local_notifications: ^17.2.1
  flutter_pdfview: ^1.3.2
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  intl: ^0.19.0
  local_auth: ^2.2.0
  mime: ^1.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  provider: ^6.0.3
  rxdart: ^0.28.0
  share_plus: ^10.0.2
  shared_preferences: ^2.2.3
  timeago: ^3.7.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/ARMM_Logo.svg
    - assets/icons/forgot_password_icon.svg
    - assets/icons/link_sent_icon.svg
    - assets/icons/onboarding.svg
    - assets/icons/login.svg
    - assets/icons/google.svg

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MADE Tommy Soft
      fonts:
        - asset: assets/fonts/MADE Tommy Soft Thin.otf
          weight: 100
        - asset: assets/fonts/MADE Tommy Soft Thin Outline.otf
          weight: 100
        - asset: assets/fonts/MADE Tommy Soft Light.otf
          weight: 300
        - asset: assets/fonts/MADE Tommy Soft Light Outline.otf
          weight: 300
        - asset: assets/fonts/MADE Tommy Soft Regular.otf
          weight: 400
        - asset: assets/fonts/MADE Tommy Soft Regular Outline.otf
          weight: 400
        - asset: assets/fonts/MADE Tommy Soft Medium.otf
          weight: 500
        - asset: assets/fonts/MADE Tommy Soft Medium Outline.otf
          weight: 500
        - asset: assets/fonts/MADE Tommy Soft Bold.otf
          weight: 700
        - asset: assets/fonts/MADE Tommy Soft Bold Outline.otf
          weight: 700
        - asset: assets/fonts/MADE Tommy Soft ExtraBold.otf
          weight: 800
        - asset: assets/fonts/MADE Tommy Soft ExtraBold Outline.otf
          weight: 800
        - asset: assets/fonts/MADE Tommy Soft Black.otf
          weight: 900
        - asset: assets/fonts/MADE Tommy Soft Black Outline.otf
          weight: 900
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
