name: Build & Deploy (Fastlane)

on:
  push:
    branches:
      - main  # or your release branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Java (required for the Android SDK and Flutter)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # 3. Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. Navigate to the Flutter app directory
      - name: Go to Flutter project
        working-directory: apps/mobile
        run: echo "In directory: $(pwd)"

      # 5. Decode the Android keystore (from base64)
      - name: Decode Keystore
        working-directory: apps/mobile
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > $HOME/android_keystore.jks

      # 6. Create key.properties (used by Gradle to sign the app)
      - name: Create key.properties
        working-directory: apps/mobile
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=${HOME}/android_keystore.jks
          EOF

      # 7. Get Flutter dependencies
      - name: Flutter Pub Get
        working-directory: apps/mobile
        run: flutter pub get

      # 8. Build the Android App Bundle
      #    This will read version info from pubspec.yaml (e.g., "version: 1.0.0+1")
      - name: Build AAB
        working-directory: apps/mobile
        run: flutter build appbundle --release

      # 9. Install Fastlane (Ruby-based)
      - name: Install Fastlane
        run: sudo gem install fastlane

      # 10. Deploy to Google Play using Fastlane "supply"
      - name: Deploy to Google Play
        working-directory: apps/mobile
        run: |
          # Decode the Google Play service account from base64 to a JSON file
          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}" | base64 --decode > service_account.json

          # Use Fastlane supply
          fastlane supply \
            --track "production" \
            --package_name "com.example.app" \
            --json_key service_account.json \
            --aab "build/app/outputs/bundle/release/app-release.aab" \
            --skip_upload_changelogs true \
            --skip_upload_metadata true \
            --skip_upload_images true \
            --skip_upload_screenshots true
