name: Build & Deploy (Fastlane)

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Go to Flutter project
        working-directory: apps/mobile

      - name: Decode Keystore
        working-directory: apps/mobile
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > $HOME/android_keystore.jks

      - name: Create key.properties
        working-directory: apps/mobile
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=${HOME}/android_keystore.jks
          EOF

      - name: Flutter Pub Get
        working-directory: apps/mobile
        run: flutter pub get

      - name: Build AAB
        working-directory: apps/mobile
        run: flutter build appbundle --release

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Deploy to Google Play
        working-directory: apps/mobile
        run: |
          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}" | base64 --decode > service_account.json
          fastlane supply \
            --track "production" \
            --package_name "com.armm.investmentportfolio" \
            --json_key service_account.json \
            --aab build/app/outputs/bundle/release/app-release.aab \
            --skip_upload_changelogs true \
            --skip_upload_metadata true \
            --skip_upload_images true \
            --skip_upload_screenshots true
